name: Package and Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Fetch Tags
        run: git fetch --tags

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Bundle
        run: |
          mkdir -p dist
          npm run changelog
          npm run bundle

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: elementor-media-validator-plugin
          path: ./dist/*.zip

      - name: Upload Changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: CHANGELOG.md

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    needs: package

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Package
        uses: actions/download-artifact@v3
        with:
          name: elementor-media-validator-plugin
          path: ./elementor-media-validator-plugin.zip

      - name: Download Package
        uses: actions/download-artifact@v3
        with:
          name: changelog
          path: ./CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
          files: |
            elementor-media-validator-plugin.zip
          draft: false
          prerelease: false
